In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

In [3]:
#Upload data file
df=pd.read_json('SafeWalk_Dummy_DatabaseML.json')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   _id               60 non-null     object
 1   locationId        60 non-null     object
 2   coordinates       60 non-null     object
 3   lighting          60 non-null     int64
 4   cctvCount         60 non-null     int64
 5   crimeIndex        60 non-null     float64
 6   crowdDensity      60 non-null     float64
 7   policeDistance    60 non-null     float64
 8   hospitalDistance  60 non-null     float64
dtypes: float64(4), int64(2), object(3)
memory usage: 4.3+ KB

In [4]:
#drop firs column
df.drop('_id',axis=1)

,locationId,coordinates,lighting,cctvCount,crimeIndex,crowdDensity,policeDistance,hospitalDistance
0,Shivajinagar,"[18.5302, 73.8526]",5,15,0.10,0.80,0.4,0.8
1,FC-Road,"[18.5293, 73.848]",5,14,0.09,0.90,0.6,1.0
2,JM-Road,"[18.5276, 73.8471]",4,12,0.12,0.85,0.7,1.2
3,Viman-Nagar,"[18.5667, 73.9145]",5,20,0.08,0.90,0.8,1.0
4,Koregaon-Park,"[18.5362, 73.895]",5,18,0.10,0.85,1.1,1.5
5,Magarpatta,"[18.5196, 73.9317]",5,25,0.07,0.70,1.4,1.6
6,Hinjewadi-Phase1,"[18.591, 73.7389]",4,14,0.10,0.75,2.0,2.5
7,Baner,"[18.559, 73.7867]",4,16,0.12,0.80,1.5,1.7
8,Aundh,"[18.557, 73.8068]",5,17,0.08,0.85,1.1,1.2
9,Balewadi-HighStreet,"[18.5642, 73.7708]",4,15,0.09,0.80,1.8,2.0
10,Kothrud,"[18.5074, 73.8077]",4,13,0.14,0.70,1.6,1.8
11,Pashan,"[18.5463, 73.8037]",4,10,0.15,0.60,2.2,2.5
12,Wakad,"[18.5916, 73.7589]",4,14,0.13,0.75,2.1,2.2
13,Model-Colony,"[18.5308, 73.8415]",5,11,0.11,0.70,0.9,1.0
14,Kalyani-Nagar,"[18.552, 73.8995]",5,19,0.10,0.85,1.3,1.4
15,Hadapsar-Gadital,"[18.501, 73.9348]",4,12,0.13,0.70,1.9,2.0
16,Camp,"[18.5183, 73.8803]",5,22,0.12,0.90,0.8,1.0
17,Deccan,"[18.516, 73.841]",5,16,0.14,0.85,0.7,1.0
18,Bibvewadi,"[18.4695, 73.866]",4,10,0.15,0.60,1.7,1.9
19,Wanowrie,"[18.488, 73.901]",5,12,0.12,0.70,1.4,1.8
20,Swargate,"[18.5008, 73.858]",3,8,0.25,0.90,0.8,1.3
21,Karve-Nagar,"[18.5036, 73.8151]",3,7,0.28,0.60,1.7,2.0
22,Narhe,"[18.457, 73.8121]",2,5,0.32,0.50,2.5,2.4
23,Sinhagad-Road,"[18.4733, 73.825]",3,8,0.30,0.70,2.0,2.5
24,Yerwada,"[18.5582, 73.8923]",3,9,0.27,0.80,1.5,1.8
25,Kharadi,"[18.551, 73.9436]",3,10,0.26,0.80,1.9,1.6
26,Dhanori,"[18.5762, 73.906]",3,6,0.30,0.60,2.2,2.5
27,Lohegaon,"[18.597, 73.9254]",2,4,0.35,0.50,3.5,3.0
28,Manjri,"[18.5201, 73.9722]",2,5,0.33,0.55,3.2,2.8
29,Katraj,"[18.4571, 73.8665]",3,7,0.31,0.70,1.9,2.1
30,Vadgaon-Budruk,"[18.4651, 73.8211]",2,6,0.32,0.55,2.4,2.7
31,Ambegaon,"[18.447, 73.8595]",3,7,0.28,0.60,2.3,2.0
32,Pimple-Gurav,"[18.586, 73.818]",3,8,0.29,0.65,2.1,2.0
33,Pimple-Saudagar,"[18.5822, 73.8048]",3,9,0.27,0.70,1.9,1.8
34,Ravet,"[18.6502, 73.7617]",2,6,0.34,0.50,3.5,3.0
35,Thergaon,"[18.6001, 73.7861]",3,7,0.29,0.60,2.4,2.2
36,Kalewadi,"[18.598, 73.8]",3,8,0.31,0.65,2.2,2.4
37,Warje,"[18.4891, 73.807]",3,7,0.28,0.65,1.8,2.0
38,Bavdhan,"[18.515, 73.7862]",3,9,0.27,0.70,2.0,2.3
39,Sus-Road,"[18.55, 73.7812]",3,7,0.30,0.55,2.4,2.6
40,Bhawani-Peth,"[18.5161, 73.8662]",2,3,0.65,0.80,1.4,1.7
41,Kasba-Peth,"[18.5212, 73.858]",2,4,0.60,0.75,1.6,1.9
42,Shukrawar-Peth,"[18.51, 73.855]",1,3,0.70,0.70,1.8,2.0
43,Nana-Peth,"[18.5186, 73.8683]",2,3,0.68,0.65,1.9,2.2
44,Camp-Backside,"[18.5142, 73.879]",2,4,0.62,0.70,1.2,1.5
45,Ghorpadi,"[18.52, 73.902]",2,3,0.63,0.60,2.1,2.3
46,Chikhali,"[18.6571, 73.8165]",1,2,0.72,0.50,4.0,3.5
47,Bhosari,"[18.6342, 73.8493]",2,4,0.65,0.60,3.0,2.8
48,Dapodi,"[18.579, 73.8292]",2,3,0.66,0.65,2.8,2.3
49,Hadapsar-Industrial,"[18.499, 73.934]",2,2,0.70,0.50,3.0,3.4
50,Kondhwa-Khurd,"[18.463, 73.893]",2,3,0.67,0.60,2.9,3.1
51,Kondhwa-BK,"[18.457, 73.899]",1,2,0.72,0.55,3.2,3.0
52,Phulenagar,"[18.5611, 73.885]",2,3,0.65,0.65,2.5,2.9
53,Gokhale-Nagar,"[18.5292, 73.8283]",1,2,0.70,0.60,2.0,2.4
54,Parvati-Paytha,"[18.4961, 73.8556]",2,3,0.64,0.70,1.6,1.9
55,Taljai-Hills,"[18.471, 73.8481]",1,1,0.75,0.40,3.0,3.2
56,Shivane,"[18.4861, 73.7862]",2,2,0.68,0.55,2.7,3.0
57,Katraj-Ghat,"[18.4501, 73.8681]",1,1,0.78,0.30,4.2,4.0
58,Pulgate,"[18.5111, 73.881]",2,3,0.62,0.75,1.8,2.0
59,Tadiwala-Road,"[18.5289, 73.876]",1,2,0.74,0.65,2.2,2.4

In [5]:
#Convert coordinates array into seperate columns
df["lat"] = df["coordinates"].apply(lambda x: x[0])
df["lon"] = df["coordinates"].apply(lambda x: x[1])
df = df.drop("coordinates", axis=1)
df=df.drop('_id',axis=1)
df.sample(5)

,locationId,lighting,cctvCount,crimeIndex,crowdDensity,policeDistance,hospitalDistance,lat,lon
53,Gokhale-Nagar,1,2,0.70,0.60,2.0,2.4,18.5292,73.8283
42,Shukrawar-Peth,1,3,0.70,0.70,1.8,2.0,18.5100,73.8550
43,Nana-Peth,2,3,0.68,0.65,1.9,2.2,18.5186,73.8683
35,Thergaon,3,7,0.29,0.60,2.4,2.2,18.6001,73.7861
47,Bhosari,2,4,0.65,0.60,3.0,2.8,18.6342,73.8493

In [6]:
#train_test_split
X = df[["lighting", "cctvCount", "crowdDensity", "policeDistance", "hospitalDistance", "lat", "lon"]]
y = df["crimeIndex"]
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [7]:
#train model using Random forest
model = RandomForestRegressor(
    n_estimators=200,
    random_state=42
)

model.fit(X_train, y_train)

RandomForestRegressor(n_estimators=200, random_state=42)

In [8]:
#pridict crime index
df["predicted_crimeIndex"] = model.predict(X)

In [9]:
#calculate risk Score
df["riskScore"] = df["predicted_crimeIndex"] * df["crowdDensity"]

In [10]:
print(df[["locationId", "predicted_crimeIndex", "riskScore"]].head())

      locationId  predicted_crimeIndex  riskScore
0   Shivajinagar               0.09960   0.079680
1        FC-Road               0.09775   0.087975
2        JM-Road               0.11695   0.099407
3    Viman-Nagar               0.08460   0.076140
4  Koregaon-Park               0.10180   0.086530

In [16]:
df.to_json("safetyData.json",orient="records",indent=2)